apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todos-server
  namespace: todos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todos-server
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
