apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: todos-gateway
   labels:
      app: todos
      tier: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todos
        tier: gateway
    spec:
      containers:
      - name: todos-gateway
        image: gcr.io/grpc-demo-1/todos-gateway
        imagePullPolicy: Always
        ports:
        - name: todos-gateway
          containerPort: 80
        env:
          - name: TODOS_BACKEND
            value: "todos-server:50051"
          - name: TODOS_CORS_ALLOW-ORIGIN
            value: "*"
          - name: TODOS_CORS_ALLOW-METHODS
            value: "GET, OPTIONS, DELETE, POST"
---
apiVersion: v1
kind: Service
metadata:
  name: todos-gateway
  labels:
    app: todos
    tier: gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: todos-gateway
  selector:
    app: todos
    tier: gateway
